name: Release and Build

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 17
    
    - name: Build and Test
      run: ./gradlew clean build
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref_name }}
        release_name: Release ${{ github.ref_name }}
        body: |
          Release ${{ github.ref_name }}
          
          ## Artifacts
          - **Plugin ZIP**: prometheus-exporter-${{ github.ref_name }}.zip (main plugin for OpenSearch installation)
          - **Plugin JAR**: prometheus-exporter-${{ github.ref_name }}.jar (compiled plugin JAR)
          - **Sources JAR**: prometheus-exporter-${{ github.ref_name }}-sources.jar (source code)
          - **Javadoc JAR**: prometheus-exporter-${{ github.ref_name }}-javadoc.jar (API documentation)
          
          ## Installation
          ```bash
          ./bin/opensearch-plugin install https://github.com/schtinkafinga/prometheus-exporter-plugin-for-opensearch/releases/download/${{ github.ref_name }}/prometheus-exporter-${{ github.ref_name }}.zip
          ```
        draft: false
        prerelease: false
    
    - name: Upload Plugin ZIP
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/distributions/prometheus-exporter-${{ github.ref_name }}.zip
        asset_name: prometheus-exporter-${{ github.ref_name }}.zip
        asset_content_type: application/zip
    
    - name: Upload Plugin JAR
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/distributions/prometheus-exporter-${{ github.ref_name }}.jar
        asset_name: prometheus-exporter-${{ github.ref_name }}.jar
        asset_content_type: application/java-archive
    
    - name: Upload Sources JAR
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/distributions/prometheus-exporter-${{ github.ref_name }}-sources.jar
        asset_name: prometheus-exporter-${{ github.ref_name }}-sources.jar
        asset_content_type: application/java-archive
    
    - name: Upload Javadoc JAR
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/distributions/prometheus-exporter-${{ github.ref_name }}-javadoc.jar
        asset_name: prometheus-exporter-${{ github.ref_name }}-javadoc.jar
        asset_content_type: application/java-archive