name: Release and Build

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: 17
    
    - name: Build and Test
      run: ./gradlew clean build
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        name: Release ${{ github.ref_name }}
        body: |
          Release ${{ github.ref_name }}
          
          ## Artifacts
          - **Plugin ZIP**: prometheus-exporter-${{ github.ref_name }}.zip (main plugin for OpenSearch installation)
          - **Plugin JAR**: prometheus-exporter-${{ github.ref_name }}.jar (compiled plugin JAR)
          - **Sources JAR**: prometheus-exporter-${{ github.ref_name }}-sources.jar (source code)
          - **Javadoc JAR**: prometheus-exporter-${{ github.ref_name }}-javadoc.jar (API documentation)
          
          ## Installation
          ```bash
          ./bin/opensearch-plugin install https://github.com/schtinkafinga/prometheus-exporter-plugin-for-opensearch/releases/download/${{ github.ref_name }}/prometheus-exporter-${{ github.ref_name }}.zip
          ```
        draft: false
        prerelease: false
        files: |
          ./build/distributions/prometheus-exporter-${{ github.ref_name }}.zip
          ./build/distributions/prometheus-exporter-${{ github.ref_name }}.jar
          ./build/distributions/prometheus-exporter-${{ github.ref_name }}-sources.jar
          ./build/distributions/prometheus-exporter-${{ github.ref_name }}-javadoc.jar
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}